# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9001
baseurl:          /
url:              http://snowdj.github.io/bootstrap
encoding:         UTF-8

# Custom vars
current_version:  3.2.0
repo:             https://http://snowdj.github.io/bootstrap
sass_repo:        https://http://snowdj.github.io/bootstrap

download:
  source:         https://github.com/twbs/bootstrap/archive/v3.2.0.zip
  dist:           https://github.com/twbs/bootstrap/releases/download/v3.2.0/bootstrap-3.2.0-dist.zip
  sass:           https://github.com/twbs/bootstrap-sass/archive/v3.2.0.tar.gz

blog:             http://snowdj.github.io/bootstrap
expo:             http://snowdj.github.io/bootstrap

cdn:
  css:            //maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css
  css_theme:      //maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css
  js:             //maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js
